version: '3.3'
services:
  app:
    build: 
      dockerfile: ./go.dockerFile
      context: .
    container_name: appGo
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - projeto-go
  db:
    image: mysql
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: 'meubanco'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '33060:3306'
    expose:
      # Opens port 3306 on the container
      - '33060'
      # Where our data will be persisted
    networks:
      - projeto-go  
    volumes:
      - ./my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
networks:
  projeto-go:
    driver: bridge